---
title: "About Me"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Education

| Master of Environmental Science & Management | Expected 2021 |
| -------------------------------------------- | -------------: |
| Bren School of Environmental Science & Management, UC Santa Barbara | *Santa Barbara, CA* |



| B.S. Environmental Management & Protection | 2016 |
| -------------------------------------------- | -------------: |
| California Polytechnic State University | *San Luis Obispo, CA* |


## Master's Group Project


| Locating prescribed fire to maximize water quality benefits in the Sierra Nevada | 4/20-Present |
| -------------------------------------------- | -------------: |
| Project Manager      | *Client:* American Rivers |


-   Built a fire- and erosion-modeling framework to recommend prescribed fire locations within Central Sierra Nevada watersheds that reduce post-fire erosion loss and protect riparian habitats and water infrastructure.
-   Co-managed a remotely distanced 5-person team which included facilitating team meetings, designing and implementing project management software, and collaborating to meet project objectives.

## Conservation Planning Experience

| State Wildlife Action Plan Intern             | 7/20-9/20 |
| -------------------------------------------- | -------------: |
| USGS Climate Adaptation Science Center (CASC) | *Remote*  |

-   Created and applied a literature-informed typology system to qualitatively analyze the inclusion of climate adaptation planning in 7 existing State Wildlife Action Plans (SWAP) to guide future CASC support and plans.
-   Developed interview framework to guide future conversations with state wildlife agency representatives.
-   Facilitated a national conversation between regional CASCs about how the network could support SWAPs.

| Conservation Planning Technician | 6/17-8/19        |
| -------------------------------------------- | -------------: |
| Sonoma County Ag + Open Space    | *Santa Rosa, CA* |

-   Coordinated over 180 individuals from 80 organizations in collaboration with superiors to develop the Living in a Fire Adapted Landscape report in response to the 2017 North Bay fires.
-   Composed content, reviewed and integrated over 4,000 public comments, and organized 7 public meetings in support of the development of the Vital Lands Initiative, a comprehensive land conservation plan.
-   Collaborated with graphic designers to develop two 40+ page reports and 12 public messaging documents in support of the Healthy Lands & Healthy Economies Initiative, an ecosystem service valuation.

| Sustainable Mapping Intern | 5/17-6/17           |
| -------------------------------------------- | -------------: |
| Greenbelt Alliance         | *San Francisco, CA* |

-   Calculated park-deficient acres in Santa Rosa and recommended areas for equitable park investment.
-   Analyzed urban park accessibility in the San Francisco Bay Area using ArcGIS to support community planning advocacy aimed at improving quality of life for marginalized communities.

## Additional Environmental Experience

| Strategic Planning Assistant | 3/20-10/20          |
| -------------------------------------------- | -------------: |
| Santa Cruz Island Reserve    | *Santa Barbara, CA* |

| LCA Research Assistant           | 10/15--6/16           |
| -------------------------------------------- | -------------: |
| Natural Resource Dept., Cal Poly | *San Luis Obispo, CA* |

| Conservation Planning Intern  | 6/15-9/15        |
| -------------------------------------------- | -------------: |
| Sonoma County Ag + Open Space | *Santa Rosa, CA* |

| GIS Intern            | 6/14-9/14        |
| -------------------------------------------- | -------------: |
| Sonoma Ecology Center | *Glen Ellen, CA* |
